"""Initial revision

Revision ID: 02f0645d7eaa
Revises:
Create Date: 2025-04-12 22:05:16.789789

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "02f0645d7eaa"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("uid"),
    )
    op.create_table(
        "properties",
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("type", sa.Enum("LIST", "INT", name="propertytype"), nullable=False),
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("uid"),
    )
    op.create_table(
        "property_values",
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("property_id", sa.Uuid(), nullable=False),
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["properties.uid"],
        ),
        sa.PrimaryKeyConstraint("uid"),
    )
    op.create_table(
        "product_properties",
        sa.Column("int_value", sa.Integer(), nullable=True),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("property_id", sa.Uuid(), nullable=False),
        sa.Column("value_uid", sa.Uuid(), nullable=True),
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.uid"],
        ),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["properties.uid"],
        ),
        sa.ForeignKeyConstraint(
            ["value_uid"],
            ["property_values.uid"],
        ),
        sa.PrimaryKeyConstraint("uid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product_properties")
    op.drop_table("property_values")
    op.drop_table("properties")
    op.drop_table("products")
    # ### end Alembic commands ###
